# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jacky Shum
tagline:          我的五餅二魚
url:              https://jkshum.github.io
paginate:         1
baseurl:          /
author:
  name:           Jacky Shum
  url:            https://
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
